name: Dart CI

on:
  push:
    branches: [ Experimental ]
  pull_request:
    branches: [ Experimental ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Sass
      run: pub global activate sass
              import 'package:sass/sass.dart' as sass;

              void main(List<String> args) {
              print(sass.compile(args.first));
              }
    - name: Install dependencies
      run: pub get;
