name: Dart CI

on:
  push:
    branches: [ Experimental ]
  pull_request:
    branches: [ Experimental ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Sass
      run: pub global activate sass
    - name: Install dependencies
      run: pub get;
    - name: Run SASS
      run: sass ./main.scss ./main.css
